### PR TITLE
Add basic Github Actions to the Blackbox Tools

### PR DESCRIPTION
**Pull request by McGiverGim**
Add basic CI to the repo.

I have tested only some of them, so not sure that all will work, but at least nightlies seem to work right.

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]
beat me to it, nice! wink
i did notice windows will be a bit more involved.
looks like admin/owner still need to disassociate Travis in order to move forward.

**Comment by McGiverGim** [comment]
Yes, windows is a little different, so I haven't tried. 
I suppose @blckmn or others have rights to merge without travis permission...

**Comment by nerdCopter** [comment]
@sugaarK , options:
image

**Comment by haslinghuis** [comment]
@blckmn please merge

**Review by blckmn — APPROVED** [review]

**Pull request merged**
