### PR TITLE
Update blackbox_decode.c

### PR DESCRIPTION
**Pull request by xsnoopy**
Added Units for simulate IMU 

Issue https://github.com/betaflight/blackbox-tools/issues/39

### CODE REVIEW

**Comment by rickmanship** [comment]
Changing the heading for no reason other than to change it means that any other tools that parse the files might break since they would be expecting different headers. I know some of the PID analysis tools consume these files so this change is likely to break them. The headings have been like this for a long time and it's never been a problem so I don't see why it should be changed.

**Comment by xsnoopy** [comment]
Unlikely that this happens IMU shouldn´t be used for PID analysis.

**Comment by dellch** [comment]
What about adding a flag, `--include-imu-units`

Also, shouldn't this be added to Units.h arrays to be consistent with the rest of the code?

**Comment by mikeller** [comment]
@xsnoopy: Can you please rebase to resolve the conflicts?

**Comment by xsnoopy** [comment]
I think it's taking care of by this pull request https://github.com/betaflight/blackbox-tools/pull/43

**Pull request closed without merging**
